### PR TITLE
Field information in table format

### PR DESCRIPTION
**Pull request by DanLipsitt**
I've created fields.csv to hold information about the spec in a compact, machine-readable format. It shows the range of possible values for each field, and how they are calculated. It also shows data types and units. This file could be used to help generate user interfaces and prose documentation, especially if we add a description column. I think it's better to generate certain parts of the code and documentation from data than to try to keep them in sync manually.

I created the file to match the current RC1 document, and than added commits for individual changes I'm proposing. I've added some fields and changed the size or range of others. This is partly based on a conversation with Lance from MadeSolid, although he has not reviewed the result. Some fields still need to be filled in.

I don't necessarily expect this to be merged wholesale. I'm submitting it so it can be reviewed and commented.

### CODE REVIEW

**Comment by miloh** [comment]
I still don't think the diameter field is right  -- just checked and I see that it's x1/100. Btw, it's easy to capture all this in a glance in a spreadsheet calculator, import the .csv into a spreadsheet program and play around with the multiplier. 

So fix that field to =1/100 

There's actually an argument to add a bit to the diameter field, given the thickest standard diameter I've seen people use is 3mm, but it's anyone's guess in the future ( some kind of crazy might use house/furniture filament with 12.52mm filament, or more).

**Comment by whosawhatsis** [comment]
Re: 12.52mm diameter, in cases like this we've had to intentionally limit the scope of the standard. If someone was using a filament that thick, it would break the math and physics currently used by printers (for instance, I can think of very few thermoplastics that I would still describe as a "filament" rather than a "rod" if they were 12.52mm in diameter. I'm not sure where the cutoff for that distinction would be (it's one of those inconvenient continuities), but 5.12mm seems like as good a maximum value for that field as any. We've all seen the video (http://vimeo.com/17358934) of full-size chairs being printed by a robot arm, but that video starts with ground up material being poured into a hopper above the extruder mechanism, and it seems likely that an arrangement like that is the only way such a large-scale extruder would be workable.

**Comment by HaveBlueXST** [comment]
Hi all - I have many thoughts on UFIDS, but I thought I'd dive in on this thread first.  Rather than using the 512 bits to store the diameter in mm, what if it instead was used to store the cross-sectional area of the filament?  After all, that's really what our printers care about - if a length of filament is oval or otherwise oblong in shape (or even square/rectangular as I've seen in some patents and even an actual commercial machine aimed at kids), our printers don't really care as long as the cross-sectional area is consistent.

What if the 512 bits (which I would expand, as I think this value deserves many more bits than color, for example) were used instead to determine cross-section?  Divide the decimal value by 25 to determine the cross-sectional area in square mm, for example.

0d000 = undefined/unknown
0d001 = out of range (in regards to the previous two comments)
0d002 = 0.08 mm^2 (0.319194 mm dia.)
0d060 = 2.4 mm^2 (1.748 mm dia.)
0d511 = 20.4 mm^2 (5.101 mm dia.)

The down side to this convention is loss of precision at 1.75mm dia. (though an increase in precision at 3mm dia.).  At 1.75mm, the current convention allows for a precision of around 0.027 mm^2 per division, while the cross-sectional area method I just proposed has a fixed precision of 0.04 mm^2 per divison, allowing for greater precision once you get up to 3mm filament ( around .047 mm^2 per division with the current diameter-based method versus the fixed 0.04 mm^2 by the area method).

And I agree that 5mm-ish is probably a decent upper limit for diameter - it's very likely that anything beyond that size would be utilizing a granule based extruder rather than filament based (can you imagine coiling a roll of 10mm polycarbonate?!?)

**Comment by whosawhatsis** [comment]
@HaveBlueXST It's not always true that out printers don't care about oval/oblong filament (it depends on the extruder mechanism, as some will bite differently, changing the effective diameter of the drive gear). Anyway, I considered tracking cross-sectional area instead of diameter, but the loss of precision on smaller-diameter filaments is not good. If anything, we would want an exponential/logarithmic curve going the other way, so the precision increases as the diameter decreases. It's also easier for filament measuring devices to return a diameter measurement to the firmware than area.

**Comment by HaveBlueXST** [comment]
I agree that the loss of precision is a major downside, especially as diameter decreases.  As well, a log based curve is really ideal!

Good, then my gut feeling that diameter is still superior to cross-sectional area still holds...  Carry on!

**Comment by nothinman** [comment]
Guys, I'm looking at implementing this standard-to-be ;) into my stickers, but the diameter and tolerance fields make me feel unappreciated.
I measure filaments before spooling with 0.0001mm resolution and 0.0005mm accuracy. Have I really just spent 12k GBP on a laser scan micrometer only to forget about the last two digits? ;P

Marcin

**Pull request merged**
