### PR TITLE
Javascript QR Codes!

### PR DESCRIPTION
**Pull request by Jnesselr**
The QR Code looks different than the one we're using now, but it scans the same. It also doesn't have a border, but I didn't know if that should be fixed or not, so I left it as is.

The javascript is modified from: https://github.com/davidshimjs/qrcodejs

### CODE REVIEW

**Comment by whosawhatsis** [comment]
What level of error correction did you use? If it's different from what we've been using, that would explain why the code looks different but decodes the same.

**Comment by Jnesselr** [comment]
L, which is what I thought you were using. Let me try different values and update the pull request.

**Comment by Jnesselr** [comment]
Nope. This is a temporary site I'm hosting it at: http://ufid.jnesselr.org/

Basically, That's L, M, Q, and H together and none of them look correct.

Also, when scanning, then reconstructing the QR code, it shows UFID.org's version.

I'm not sure if we need to be worried about it if it scans correctly, but I'd like to know why it's different at least.

**Comment by whosawhatsis** [comment]
Yeah, the L is close, but it's a slightly larger code, as if there was a little additional padding on the data that meant that it needed to encode to a slightly larger square.

**Comment by RavinMaddHatter** [comment]
The code is different because, the html encoded in the QR is different, For that Charts APP i cannot send # so i send %23 (the code for #, i wrote this into the library for cleaner looking code in index.html), There are 2 URLs being made, one for passing thought to google, one for direct manipulation (i apologize it was a hack to get things working). 

everything will work if you use
object.url
It will not work with 
object.qr_url

I could fix it, but you want it fixed in your fork. Because i am a GIT Noob, should i accept the PR and then fix it or should i let you fix it and submit a new PR.

**Comment by Jnesselr** [comment]
I don't now why I said encoded url, I meant the one that wasn't encoded. Ah well, either way. I can't find a javascript library that allows you to do a qr code with no error correction, so I think it's okay to keep it with the lowest level. If you agree, then it should be safe to merge it in.

As for merging in branches in general, I prefer to keep my git graph as clean as possible. If something isn't done, then I don't like merging it into the main branch.

**Comment by RavinMaddHatter** [comment]
No worries, Now they look identical, i was hesitant to accept the pull request until we found out why they were different.  thanks

**Pull request merged**
